### ISSUE TITLE
VS 2013 support?

### ISSUE THREAD

**Issue by vorou** [cromwellryan/Gister#10]
As far as I can see there is no 2013 support for now, will you implement it?

**Comment by jcreamer898** [comment]
pleez i can haz? k thnkxbye

:wink:

**Comment by cromwellryan** [comment]
I'll see what I can do.  I don't do much VS dev any longer, so if you want quick turn around you can add a 12.0 version [here](https://github.com/cromwellryan/Gister/blob/master/Gister/source.extension.vsixmanifest#L20-L24) and build the extension.

**Comment by jcreamer898** [comment]
Is that all it takes?! Lol—
