### ISSUE TITLE
Enable Support for 2 factor authentication

### ISSUE THREAD

**Issue by veteran29** [cromwellryan/Gister#13]
It's is not possible to login to GitHub with Gister when 2fa is enabled.

**Comment by billmoling** [comment]
I just learn something about this. I can have a try

**Comment by cromwellryan** [comment]
@billmoling that would be amazing.

**Comment by veteran29** [comment]
@billmoling I'm not sure but i think easiest way to enable it will be to just allow for empty password field so user could provide Personal Acces Token (you can generate it here https://github.com/settings/applications ) as username.

**Comment by nate456789** [comment]
Logging in every time is a killer for me. Is there any update on at least staying logged in?

**Comment by cromwellryan** [comment]
I'd love to @nate456789, but I just don't use Visual Studio anymore :frowning:.
