### ISSUE TITLE
update to vs2013

### ISSUE THREAD

**Issue by jimmy0415** [cromwellryan/Gister#14]
Hi, 
Thanks very much for your great work! Are you going to update it to work in VS2013? Thanks very much!

**Comment by cromwellryan** [comment]
Kinda - I'm no longer using VS, but others have made the necessary modifications to support VS2013 in PR #11.  I don't have a VSIX to publish at this time, but you can clone or download the source, build locally and double click the VSIX to start using it while waiting for the gallery update.

**Comment by vorou** [comment]
[here's the VSIX](https://github.com/vorou/Gister/raw/master/Bin/Gister.vsix), sorry for the delay
it would be cool if you could publish it

**Comment by cromwellryan** [comment]
I'll get it published shortly.

**Comment by cromwellryan** [comment]
@vorou can you bump the version to 1.5?

![image](https://cloud.githubusercontent.com/assets/129756/3121931/43bf426e-e761-11e3-98d0-b9516604088f.png)

**Comment by vorou** [comment]
@cromwellryan [done](https://github.com/vorou/Gister/raw/master/Bin/Gister.vsix)

**Comment by cromwellryan** [comment]
Sorry for the delay on that update.  I've published 1.5 with 2013 support.

I saw that 2014 CTP came out recently.  I'll push that if someone wants to rebuild :smile:.
