### ISSUE TITLE
Possibility to post a private gist

### ISSUE THREAD

**Issue by toburger** [cromwellryan/Gister#5]
It would be nice if it is possible to create a private gist.
I use gist often to share some code snippets with another person, but it is extremely domain specific so it is rarely the case that it is of good use for other people...

**Comment by billmoling** [comment]
yes, in my pull request, it has the function which you can set the Private for the gist. I will work with the owner to get the pull request verified ASAP

**Comment by cromwellryan** [comment]
This was added in version 1.4.  http://cromwellryan.github.com/Gister/
